export type Language = 'fr' | 'en';

const SAVE_KEY = 'sanguine.save.v1';
const LANGUAGE_KEY = 'sanguine.language';

/**
 * The language is read before the data modules are initialised, so content definitions can
 * be localised once and stay plain strings everywhere else in the game. Changing language
 * reloads the page from the options screen.
 */
export function language(): Language {
  try {
    const stored = localStorage.getItem(LANGUAGE_KEY);
    if (stored === 'fr' || stored === 'en') return stored;

    const raw = localStorage.getItem(SAVE_KEY);
    const value = raw ? JSON.parse(raw)?.options?.language : undefined;
    if (value === 'fr' || value === 'en') {
      localStorage.setItem(LANGUAGE_KEY, value);
      return value;
    }

    const detected: Language = navigator.language.toLowerCase().startsWith('fr') ? 'fr' : 'en';
    localStorage.setItem(LANGUAGE_KEY, detected);
    return detected;
  } catch {
    return typeof navigator !== 'undefined' && navigator.language.toLowerCase().startsWith('fr') ? 'fr' : 'en';
  }
}

export function setLanguage(value: Language): void {
  try {
    localStorage.setItem(LANGUAGE_KEY, value);
  } catch {
    // Storage can be unavailable in private or sandboxed browsing contexts.
  }
}

export function t(fr: string, en: string): string {
  return language() === 'en' ? en : fr;
}

export function locale(): string {
  return language() === 'en' ? 'en-GB' : 'fr-FR';
}

export function applyDocumentLanguage(): void {
  const lang = language();
  document.documentElement.lang = lang;
  if (lang !== 'en') return;
  const content: Record<string, string> = {
    'meta[name="description"]': 'Sanguine — survive for thirty minutes. Dawn will not come.',
    'meta[property="og:title"]': 'Sanguine — survive for thirty minutes',
    'meta[property="og:description"]': 'A browser-based survivor-like. You never fire: your weapons trigger automatically. Everything is generated by code; nothing is downloaded.',
    'meta[property="og:image:alt"]': 'The bleeding Sanguine logo above a moonlit moor and a row of creatures.',
    'meta[name="twitter:title"]': 'Sanguine — survive for thirty minutes',
    'meta[name="twitter:description"]': 'A browser-based survivor-like. Zero dependencies, zero binary assets: everything is generated by code.',
    'meta[property="og:locale"]': 'en_GB',
  };
  for (const [selector, value] of Object.entries(content)) {
    document.querySelector<HTMLMetaElement>(selector)?.setAttribute('content', value);
  }
}

type LocalisedFields = Record<string, string>;

/** Applies an English overlay to content objects while preserving their stable IDs. */
export function localiseById<T extends { id: string }>(
  entries: T[],
  english: Record<string, LocalisedFields>,
): void {
  if (language() !== 'en') return;
  for (const entry of entries) {
    const translated = english[entry.id];
    if (translated) Object.assign(entry, translated);
  }
}
